### PR TITLE
Changed wrfout in order to incorporate SINALPHA and COSALPHA for earth-rel wind calc

### PR DESCRIPTION
**Pull request by lpilz**

### CODE REVIEW

**Comment by lpilz** [comment]
I took the first 100 (resp. 101 for staggered) data points per dimension because the file would have been too big otherwise.

**Comment by jthielen** [comment]
Since I don't expect anyone/anything to be using the "wrfout" dataset other than our own doc's tutorials at this point, I don't see any issues with this being a replacement rather than addition.

> I took the first 100 (resp. 101 for staggered) data points per dimension because the file would have been too big otherwise.

Have you confirmed that the computed dimension coordinates from `.xwrf.postprocess()` are correct given this subsetting? If I recall correctly, those are computed based on `CEN_LON` and `CEN_LAT`, so unless it is a centered subset, they may be incorrect.

**Comment by lpilz** [comment]
Yes, very good catch. But isn't that a bug? At the moment it reads:

https://github.com/xarray-contrib/xwrf/blob/d3c451b87a900a5c7887837460dfe36526dbd429/xwrf/grid.py#L63-L76

And if you change the calculation of the lower left corner to the following, it would be more robust.
```
    nx = ds.attrs['WEST-EAST_GRID_DIMENSION']
    ny = ds.attrs['SOUTH-NORTH_GRID_DIMENSION']
    x0 = -(nx - 1) / 2.0 * dx + e  # DL corner
    y0 = -(ny - 1) / 2.0 * dy + n  # DL corner
    nx = ds.dims['west_east']
    ny = ds.dims['south_north']

```

I know that this doesn't fix everything but if you after the  set `nx` and `ny` to `dims['west_east']` and `dims['south_north']`, you can at least slice from the lower left corner. I racked my brain over how to make this as robust as possible, but I could only come up with transforming the lat/lons into x/y using the transformer. Do you have a better idea? Because I find it a bit unintuitive that I can't slice raw WRF datasets.

**Comment by lpilz** [comment]
Alright, I thought a bit about this (and maybe this is something we could do for xWRF v0.0.3):

If we have a sliced subset, what we are missing is the location of the lower left corner in x/y coordinates. We can find this by iteratively transforming the superset x/y coordinates into lat/lons and comparing them to the known lat/lon of the lower left corner of the subset. This way we don't have to transform the whole x/y coordinate array, as this will probably be expensive. To speed things up, we could probably use a Newton-method-like approach. What do you think?

**Comment by lpilz** [comment]
I just added the full dataset (~50MB) so we can just get this over the finish line. We can deal with subsetting in future versions, for now this will hopefully be alright.

**Review by jthielen — APPROVED** [review]
I agree that just using the full dataset is good for now to get us over the finish line.

Just my quick thoughts on the subsetting issue: raw WRF output's coordinate referencing is really fragile precisely because of how it is stored in the dataset attributes; as soon as you subset spatially, you break/corrupt it. I'd say this is an argument for instructing users to only subset spatially *after* post-processing (since this is just one more fault of raw WRF), rather than trying to accommodate such metadata corruption in core functionality. That being said, I wouldn't want xwrf to only be usable by those with "pristine" raw WRF files. I'd envision supporting such "non-standard" WRF output by exposing the individual components of `postprocess` in as atomized a way as possible, so that users can pick and choose what they need or what is capable of still working with their files (this would likely include splitting apart the CRS creation from the projection coordinate creation, since only the latter is corrupted by subsetting raw output). Also, we could add alternative methods (like the suggested coordinate referencing from `XLAT` and `XLONG` rather than `CEN_LON` and `CEN_LAT`) as a part of this too.

**Pull request merged**
